### ISSUE TITLE
Error "Could not find implementations of custom rules"

### ISSUE THREAD

**Issue by mark-langer** [ReactiveX/rxjs-tslint#16]
Hi team,

the idea for the package is great! I cannot get it to work though following the steps in the [migration guide](https://github.com/ReactiveX/rxjs/blob/master/MIGRATION.md) though.

After installing rxjs-tslint, adding the file `migrate-rxjs.tslint.json` and running the command `./node_modules/.bin/tslint -c migrate-rxjs.tslint.json --project src/tsconfig.app.json --fix` I get the following error:

`Could not find implementations for the following rules specified in the configuration:
    update-rxjs-imports
    migrate-to-pipeable-operators
    migrate-static-observable-methods
    collapse-rxjs-imports
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.

No valid rules have been specified`

Am I doing something wrong or is this a bug within the package? I tried uninstalling TSLint, delete the global rules file and re-install it. But to no avail. I even tried removing all rules from that TSLint file to test if any of them is corrupted.

There is a folder at `node_modules/rxjs-tslint`. It looks like this:
![image](https://user-images.githubusercontent.com/18142114/39035042-dff86ae8-4478-11e8-8036-52703c191f60.png)

tslint@5.9.1
rxjs-tslint@0.1.0

**Comment by euangoddard** [comment]
I'm getting this error too for the same versions. I managed to successfully run this the other day, and I'm pretty sure it was the same version of `tslint`

**Comment by mgechev** [comment]
Will take a look today.

**Comment by mgechev** [comment]
Should be working fine now.

**Comment by euangoddard** [comment]
Thanks for looking into this especially given that you were at ng-conf!

**Comment by iget-master** [comment]
I'm still having this issue.

```
$ ./node_modules/.bin/tslint -c migrate-rxjs.tslint.json --project src/tsconfig.app.json --fix

Could not find implementations for the following rules specified in the configuration:
    rxjs-proper-imports
    rxjs-pipeable-operators-only
    rxjs-no-static-observable-methods
    rxjs-collapse-imports
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
        
No valid rules have been specified
```

**Comment by mgechev** [comment]
What version of `rxjs-tslint` are you using?

**Comment by iget-master** [comment]
Solved the problem. I was following some angular or rxjs doc that was telling to call the rxjs-tslint from project node_modules instead of the global `rxjs-5-to-6-migrate` command.
