### ISSUE TITLE
Change rule names

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs-tslint#17]
The current rule names hint at them only being useful as migration tools. They're actually useful for normal linting as well. I think we should rename them to reflect their lint purpose, rather than their migration use.

1. Prefix them with `rxjs-`
2. Change the names slightly to reflect their usage as linting rules.

 name | configuration | description 
-- | -- | --
rxjs-collapse-imports | none | Collapses multiple imports from rxjs to a single one.
rxjs-pipeable-operators-only | none | Migrates side-effect operators to pipeables.
rxjs-no-static-observable-methods | none | Migrates static Observable method calls
rxjs-proper-imports | none | Updates RxJS 5.x.x imports to RxJS 6.0

**Comment by mgechev** [comment]
Makes sense. I'll open a PR today.
