### ISSUE TITLE
How do I use this project?

### ISSUE THREAD

**Issue by giggio** [ReactiveX/rxjs-tslint#21]
I am on a  just created Angular 6 RC project. I added rxjs-lint, but tsline complains.

Here is my `src/tslint.json`:

````json
{
  "extends": [
    "../tslint.json",
    "rxjs-tslint"
  ],
  "rules": {
    "rxjs-collapse-imports": true,
    "rxjs-pipeable-operators-only": true,
    "rxjs-no-static-observable-methods": true,
    "rxjs-proper-imports": true,
    "directive-selector": [true, "attribute", "app", "camelCase"],
    "component-selector": [true, "element", "app", "kebab-case"]
  }
}
````

I get this error when I run `tslint --project .\tsconfig.app.json` from the `src` directory:

````
Could not find implementations for the following rules specified in the configuration:
    rxjs-collapse-imports
    rxjs-pipeable-operators-only
    rxjs-no-static-observable-methods
    rxjs-proper-imports
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
````

I tried adding, as per your tests to a .ts file:

````ts
import { foo } from 'rxjs';
import { bar } from 'rxjs';
````

But got no warnings.

I am using tslint `5.9.1`.

**Comment by mgechev** [comment]
Here's how you can add custom rules https://palantir.github.io/tslint/usage/tslint-json/ (see `rulesDirectory`).

The readme explains how to migrate your project.

**Comment by giggio** [comment]
Thanks, that worked.

**Comment by tony-gutierrez** [comment]
I think you need better examples of automatic code updating. I ran the migrate command and all it did was modify my imports. It didn't touch any more of the code or replace any of the now erroring operator chains.

**Comment by mgechev** [comment]
It is supposed to perform complete migration. Would you share a minimal demo where we can reproduce the problem?

**Comment by tony-gutierrez** [comment]
Sorry, my problem was that I did not realize that the migration was dependent on rxjs-compat being used in the project code.
