### ISSUE TITLE
Error when running rxjs-5-to-6-migrate

### ISSUE THREAD

**Issue by Ionaru** [ReactiveX/rxjs-tslint#34]
Installed `rxjs-tslint` globally, attempting to upgrade my Angular application from version 5 to 6.

I'm using the command
```
rxjs-5-to-6-migrate -p src/tsconfig.app.json
```

But it results in this error
```
Running the automatic migrations. Please, be patient and wait until the execution completes.
child_process.js:644
    throw err;
    ^

Error: Command failed: /usr/lib/node_modules/rxjs-tslint/node_modules/.bin/tslint -c /usr/lib/node_modules/rxjs-tslint/rxjs-5-to-6-migrate.json -p src/tsconfig.app.json --fix
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at migrate (/usr/lib/node_modules/rxjs-tslint/rxjs-5-to-6-migrate.js:18:34)
    at Object.<anonymous> (/usr/lib/node_modules/rxjs-tslint/rxjs-5-to-6-migrate.js:25:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```
There are no spaces in the path to any of the files.
I have tried specifying the full path to `tsconfig.app.json`, same result.

Linux Kubuntu 18.04
Node 8.11.1
NPM 6.0.0
Installed packages:
```
/usr/lib
├── @angular/cli@6.0.0
├── npm@6.0.0
├── rxjs-tslint@0.1.3
├── tslint@5.10.0
└── typescript@2.7.2
```

**Comment by cec** [comment]
I have the same issue.

Windows 10
Node 8.9.4
NPM 5.6.0

tslint@5.10.0
typescript@2.7.2
rxjs-tslint@0.1.3

**Comment by flauc** [comment]
Same thing also on windows 

Windows 10
Node 9.3.0
NPM 6.0.0

tslint@5.10.0
typescript@2.7.2
rxjs-tslint@0.1.3

**Comment by blackholegalaxy** [comment]
On macOS it's the same

```
macOS 10.13.4
Node 9.3.0
npm 6.0.0

tslint@5.10.0
typescript@2.7.2
rxjs-tslint@0.1.3
```

**Comment by loicsalou** [comment]
same issue for me, Win7, node64

c:\tools\npm
+-- @angular/cli@6.0.0
+-- @compodoc/ngd-cli@2.0.0-alpha.5
+-- npm@5.5.1
+-- npm-check-updates@2.13.0
+-- rimraf@2.5.4
+-- rxjs-tslint@0.1.3
+-- source-map-explorer@1.5.0
+-- standard-version@4.2.0
+-- tslint@5.10.0
`-- typescript@2.7.2

**Comment by cbchenoweth** [comment]
Same error here.
Looking at the error stack, I think this is the culprit:

![filenotfound](https://user-images.githubusercontent.com/1555628/39836981-f357570a-5389-11e8-95d0-f2a8568fbc2d.png)

**Comment by mgechev** [comment]
@cbchenoweth thanks for sharing! In such case, you should be able to workaround the issue by running:

```
npm i -g tslint
```

**Comment by mgechev** [comment]
@cbchenoweth you don't have to use a global binary. Since these are tslint rules, you can apply them with local tslint installation & the config from the repo.

The global just makes it more convenient.

**Comment by cbchenoweth** [comment]
ok, so, just to make sure my understanding is correct:
The command "rxjs-5-to-6-migrate" is essentially just doing a "tslint --fix"?

So, as long as I did the steps to set up the rules directly in my tslint.json,
the command is really not needed?

**Comment by mgechev** [comment]
@cbchenoweth correct

**Comment by cbchenoweth** [comment]
@melodysummer
If you want to run the "rxjs-5-to-6-migrate" command, I think you must also install this package globally.
So:
`npm install rxjs-tslint`

**Comment by alexeden** [comment]
If you run an `npm install` from inside the rxjs-tslint package's directory, it'll make sure it has `tslint` available. No need to be gross and install anything globally.

1. `cd node_modules/rxjs-tslint`
2. `npm install`
3. `cd ../..`
4. `./node_modules/.bin/rxjs-5-to-6-migrate -p src/tsconfig.app.json`

For bonus points, use `npx` to access the binary (I found out recently it ships with npm): 
`npx rxjs-5-to-6-migrate -p src/tsconfig.app.json`

**Comment by sandraandonov88** [comment]
I am experiencing the same error.

Windows 10
Node 9.3.0
NPM 6.0.0

tslint@4.5.1
typescript@2.6.2
rxjs-tslint@0.1.4

**Comment by leiturix** [comment]
I think that the problem is another.
Look at into the /src if the name file is ''tsconfig.app.json" or is "tsconfig.json"
In my case, i only changed to correct name.

**Comment by MickL** [comment]
Install globally or (better?) use npx: `npx rxjs-5-to-6-migrate -p src/tsconfig.app.json`

**Comment by grumpy-programmer** [comment]
In [Angular Update Guide | 5.2 -> 6.0 for Advanced Apps](https://update.angular.io/) checklist step `Choose a value of off for preserveWhitespaces in your tsconfig.json to gain the benefits of this setting while the default is still to preserve whitespace.` causes the problem.

Running `rxjs-5-to-6-migrate -p ./src/tsconfig.app.json` (no matter global or local installed) an error occurred: 
```
./node_modules/.bin/rxjs-5-to-6-migrate -p ./src/tsconfig.app.json
Running the automatic migrations. Please, be patient and wait until the execution completes.
child_process.js:644
    throw err;
    ^

Error: Command failed: "project_path/node_modules/rxjs-tslint/node_modules/.bin/tslint" -c "project_path/node_modules/rxjs-tslint/rxjs-5-to-6-migrate.json" -p "./src/tsconfig.app.json" --fix
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at migrate (project_path/node_modules/rxjs-tslint/rxjs-5-to-6-migrate.js:18:34)
    at Object.<anonymous> (project_path/node_modules/rxjs-tslint/rxjs-5-to-6-migrate.js:25:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

executing
`project_path/node_modules/rxjs-tslint/node_modules/.bin/tslint -c "project_path/node_modules/rxjs-tslint/rxjs-5-to-6-migrate.json" -p "./src/tsconfig.app.json" --fix`
we get:
`tsconfig.json(10,5): error TS5023: Unknown compiler option 'preserveWhitespaces'.`

so removing `preserveWhitespaces` solved the problem for me

**Comment by b-mi** [comment]
After installing tslint, typescript globally and locally - despite of false npm warnings about typescript missing - rxjs-5-to-6-migrate -p src/tsconfig.app.json helped. Documentation is bad - "rxjs-5-to-6-migrate -p [path/to/tsconfig.json]" is bad description. Cannot use tsconfig.json, cannot use "rxjs-5-to-6-migrate -p" without optional path. Have to use rxjs-5-to-6-migrate -p src/tsconfig.app.json.

Correct documentation.

**Comment by ziacik** [comment]
For me, running the failed command mentioned in the error, e.g. `/usr/lib/node_modules/rxjs-tslint/node_modules/.bin/tslint -c /usr/lib/node_modules/rxjs-tslint/rxjs-5-to-6-migrate.json -p src/tsconfig.app.json`, revealed me the real error.

For me, it was a messed up tsconfig.json: `tsconfig.json(11,3): error TS5023: Unknown compiler option 'preserveWhitespaces'`

**Comment by krishna-kumar06** [comment]
Please check path of tsconfig.json. In my case it was src/tsconfig.app.json but i changed it to src/client/tsconfig.json and its working.
So i did 2 changes
1) correct name of tsconfig.json (removed app)
2) correct path of this file

**Comment by mgechev** [comment]
I can see a few [solutions](https://github.com/ReactiveX/rxjs-tslint/issues/34#issuecomment-391936933) to the problem here.

**Comment by sayantansinha** [comment]
@ziacik Thanks, your solution worked for me, running the failed command showed the actual error and now it is running :)

However, this is what the angular update guide says which is why I added it in the first place, something doesn't add up, as it seems like this is not a valid option in the tsconfig file

> Choose a value of off for preserveWhitespaces in your tsconfig.json to gain the benefits of this setting while the default is still to preserve whitespace.

**Comment by candidJ** [comment]
I'm getting 'Cannot find any possible migrations' after running the migration command

**Comment by royakaacky** [comment]
> 
> 
> If you run an `npm install` from inside the rxjs-tslint package's directory, it'll make sure it has `tslint` available. No need to be gross and install something globally.
> 
>     1. `cd node_modules/rxjs-tslint`
> 
>     2. `npm install`
> 
>     3. `cd ../..`
> 
>     4. `./node_modules/.bin/rxjs-5-to-6-migrate -p src/tsconfig.app.json`
> 
> 
> For bonus points, use `npx` to access the binary (I found out recently it ships with npm):
> `npx rxjs-5-to-6-migrate -p src/tsconfig.app.json`

Why it is necessary to call 'npm install' inside the 'node_modules/rxjs-tslint' folder? It works. But i dont understand why. When i call npm install rxjs-tslint, i assume, that all dependecies will be installed.

Can you explain me this, please?

**Comment by liwonder** [comment]
I have this issue also when I try to update my Angular5 project to V7. After I tried all the above but still can't get any thing done.
Finally I found some clue other where, you should **_update your typescript globally_** as well, that seems works for me.

**Comment by moshmage** [comment]
@candidJ did you ever fix that or did you have to re-write every sibscribe by hand? (I'm getting the same output)

**Comment by Diandres** [comment]
> I think the problem is another one.
> Look at into the /src if the name file is ''tsconfig.app.json" or is "tsconfig.json"
> In my case, i only changed to correct name.

this guy is a genius

**Comment by PineauSullivan** [comment]
Hi,
I have a problem when I execute the command :
`./node_modules/.bin/rxjs-5-to-6-migrate -p src/tsconfig.app.json`

I have the following error (in french) :

`Running the automatic migrations. Please, be patient and wait until the execution completes.`
`Le chemin d'accès spécifié est introuvable.`
`Error while running the migration: ,,Le chemin d'accès spécifié est introuvable.`

Do you have an idea to help me ? 

Thank you for the help

**Comment by ginid-mansa** [comment]
> @cbchenoweth thanks for sharing! In such case, you should be able to workaround the issue by running:
> 
> ```
> npm i -g tslint
> ```

This worked for me
thanks
