### ISSUE TITLE
Specify path for rxjs-5-to-6-migrate

### ISSUE THREAD

**Issue by mxchange** [ReactiveX/rxjs-tslint#35]
It would be really helpful if I could pass a path to `rxjs-5-to-6-migrate` in order to migrate in chunks, because our code base is too big to do at once.

So something like:

`rxjs-5-to-6-migrate -P [path/to/some/route-module] -p [path/to/tsconfig.json]`

I've tried modifying `baseUrl` in tsconfig.json, but it's ignored.

**Comment by mgechev** [comment]
You can have multiple `tsconfig.json` files corresponding to the lazy-loaded modules in your application. This way you can migrate your application incrementally. Otherwise, it's not easy to migrate partially if the individual modules cannot be compiled separately since the rules use type checking.
