### ISSUE TITLE
Messy imports with rxjs-5-to-6-migrate

### ISSUE THREAD

**Issue by mxchange** [ReactiveX/rxjs-tslint#36]
## Issues
- It appends a new line at the start of most imports/files
- It adds a new line in between
- It moves rxjs imports to the top
- It does not add spaces between the brackets

Examples:
```

import {of as observableOf} from 'rxjs';

import {take} from 'rxjs/operators/take';
import { Injectable } from '@angular/core';
...
```
```

import {fromEvent as observableFromEvent} from 'rxjs';

import {map} from 'rxjs/operators/map';

import {takeUntil} from 'rxjs/operators/takeUntil';
import { ChangeDetectionStrategy, Component, EventEmitter, Input, OnDestroy, OnInit, Output } from '@angular/core';
import { Observable } from 'rxjs';

import { UploadFile } from '@core/models';
...
```

The one about the spaces might be a bit opinionated, but it would be nice to be able to configure, because this is a lot of manual labour to fix, unless someone has a clever script or plugin for webstorm to fix that :)

But the new line thing should definitely not happen.

**Comment by mgechev** [comment]
Hey @mxchange, the tool doesn't perform automated code formatting. You can use [prettier](https://github.com/prettier/prettier) or [clang-format](https://github.com/angular/clang-format) once you run the migrations.
