### ISSUE TITLE
rxjs-5-to-6-migrate appends comma

### ISSUE THREAD

**Issue by mxchange** [ReactiveX/rxjs-tslint#37]
It appends a comma after each refactored `.pipe` item:

`),)`

Like:

```
 .pipe(takeUntil(this.componentDestroyed$),)
```

**Comment by mgechev** [comment]
This comma is valid syntactically. In case you prefer to not have it in your code base, you can use [prettier](https://github.com/prettier/prettier) or [clang-format](https://github.com/angular/clang-format) once you run the migrations.
