### ISSUE TITLE
Error after running npm install -g rxjs-tslint

### ISSUE THREAD

**Issue by kajdzo** [ReactiveX/rxjs-tslint#42]
After updating from angular 5.2 to angular 6 I'm trying to run npm install -g rxjs-tslint but I keep getting following warning: 
npm WARN rxjs-tslint@0.1.4 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
+ rxjs-tslint@0.1.4
updated 2 packages in 5.813s

Even though I have "tslint": "^5.0.0" installed.

 I can't run rxjs-5-to-6-migrate -p src/tsconfig.app.json 

Anyone can help with this?

 "dependencies": {
        agm/core: "^1.0.0-beta.3",
        angular/animations: "^6.0.3",
        angular/common: "^6.0.3",
        angular/compiler: "^6.0.3",
        angular/core: "^6.0.3",
        angular/forms: "^6.0.3",
        angular/platform-browser: "^6.0.3",
        angular/platform-browser-dynamic: "^6.0.3",
        angular/platform-server: "^6.0.3",
        angular/router: "^6.0.3"
}
angular/cli: "^6.0.7",
Node : v8.11.2
Win 7

**Comment by mgechev** [comment]
If you're installing`rxjs-tslint` with `-g` install `tslint` the same way.

**Comment by arunk13** [comment]
@mgechev : If I try to install tslint globally, i get the below error. 

npm WARN tslint@5.11.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev but none is installed. You must install
peer dependencies yourself.
npm WARN tsutils@2.29.0 requires a peer of typescript@>=2.1.0 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev || >=2.4.0-dev || >=2.5.0-dev || >=2.6.0-dev || >=2.7.0-dev || >=2.8.0-dev || >=2.9.0-dev || >= 3.0.0-dev || >= 3.1.0-dev but none is installed. You must install peer dependencies yourself.

**Comment by rebekahw** [comment]
I got the same issue here, and like to know how this fixed

**Comment by felipe-b-oliveira** [comment]
Same issue here
