### ISSUE TITLE
javascript migration guide

### ISSUE THREAD

**Issue by prateekrastogi** [ReactiveX/rxjs-tslint#48]
Hi,
I am trying to use this package to migrate rxjs 5 code written in javascript. I am thrown various errors, and in the end after fixing those dependency bugs i got:
Running the automatic migrations. Please, be patient and wait until the execution completes.
Cannot find any possible migrations

I want to know whether there is some guide to help migrate javascript rxjs code, or is this even  possible with this package? As typescript is superset of js, I guess it might be possible to do so but lack of any clear guide makes the  process quite unreliable. I have to migrate 2k-3k lines of nodejs based rxjs code, and would surely not love to mess anything working. Although, I can use rxjs-compat to keep legacy code, but moving forward it would be just another contextual penalty for programmer working on that codebase.

**Comment by mgechev** [comment]
This repository works only with TypeScript. For migration guidelines check [this](https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md).
