### ISSUE TITLE
How to use the rules in Webstorm

### ISSUE THREAD

**Issue by xuko** [ReactiveX/rxjs-tslint#58]
Hello, I'm using "tslint": "5.11.0" and "rxjs-tslint": "0.1.5",

And I'd like to show as errors in webstorm the rules.

```
{
  "rulesDirectory": [
    "node_modules/rxjs-tslint"
  ],
  "rules": {
    "rxjs-collapse-imports": true,
    "rxjs-pipeable-operators-only": true,
    "rxjs-no-static-observable-methods": true,
    "rxjs-proper-imports": true
  }
}
```

I added that rules to my tslint.json but nothing happens, am I doing something wrong?

Thanks

**Comment by mgechev** [comment]
The current set of rules is intended for migration. You should run them once against your project in order to migrate your source code to rxjs@6.
