### ISSUE TITLE
Migrating TsLint to EsLint

### ISSUE THREAD

**Issue by break7533** [ReactiveX/rxjs-tslint#67]
Will the migration affect the way this plugin works?

For the moment we create the rules in a tslint.json file. While migrating to ESlint this will disappear. Is it possible to add the rule to an eslint.json file and keep the plugin alive or will it require more work?

**Comment by imbsky** [comment]
+1

**Comment by lorenzodallavecchia** [comment]
Did someone ever try using these rules with ESLint?
In my project, I use ESLint exclusively since TSLint is now deprecated.

**Comment by break7533** [comment]
Yeah, in the meanwhile in the projects I work on we just moved all the rules to the eslint.json file and everything works dandy

**Comment by lorenzodallavecchia** [comment]
@break7533 do you have an example of how to use `rxjs-tslint` with ESLint?
I'm trying to configure the rules in `eslintrc.js` but it always errors out saying that the rule definition was not found.

**Comment by break7533** [comment]
We are now using `eslint-plugin-rxjs`

And on .eslintrc.json we just add the rules, example

```
"rules": {
        "rxjs/no-internal": "error",
        "rxjs/no-async-subscribe": "error",
        "rxjs/no-nested-subscribe": "error",
        "rxjs/no-unbound-methods": "error",
}
```

**Comment by lorenzodallavecchia** [comment]
Yeah, I have tried `eslint-plugin-rxjs`.
The bad part is that it does not have a rule for detecting usages of non-pipeable operators.
I guess I'll have to live with that.
